### ISSUE TITLE
Advanced filtering ie filter by any defined data type?

### ISSUE THREAD

**Issue by hemicyon** [tokenshift/obsidian-page-gallery#20]
Is it currently possible to filter by more than folder and file names? I’ve tried adding custom data types inline and in the front matter, but the search field doesn’t recognise them. If not, it looks like using tags might be a workaround for now, which (thinking about it now) I suppose indicates that only explicit data types are supported.

**Comment by tokenshift** [comment]
Currently the filter only looks at page paths and tags. I've been planning to expand that at some point, though.

**Comment by tokenshift** [comment]
The filter now looks at page paths, tags, and any other fields defined in either page frontmatter or inline (obsidian-dataview style). It *does not* currently look in the additional fields defined in the `fields` page-gallery setting, since those can be arbitrary dataview expressions and are sometimes expensive to compute en masse.

This is available in version 0.7.2. Let me know if you see any issues.
