### ISSUE TITLE
Support for Notes gallery

### ISSUE THREAD

**Issue by SalahAdDin** [tokenshift/obsidian-page-gallery#28]
We are planning to create a gallery book for our vault, we were thinking about this plugin but it seems it only supports images, are you thinking of adding full support for notes?

Thank you.

**Comment by tokenshift** [comment]
I wasn't planning to, the intent was just to show images pulled from the listed pages. I'll keep this issue open until I get a chance to experiment w/ displaying other page content, but it likely won't be any time soon.

**Comment by tokenshift** [comment]
For a bit more information: are you looking for something to display notes Google Keep-style, or like a Notion gallery falls back to displaying text if the pages don't have any images in them?

**Comment by SalahAdDin** [comment]
> For a bit more information: are you looking for something to display notes Google Keep-style, or like a Notion gallery falls back to displaying text if the pages don't have any images in them?

Yeah, that Notion feature.

**Comment by tokenshift** [comment]
@SalahAdDin I've got a sort-of working prototype that displays page content instead of just images, depending on what mode you select. It's not available in the published page-gallery plugin yet (I want to do more testing before I push it out), but I have it in a forked repo at https://github.com/tokenshift/obsidian-page-gallery-notes-prototype; if you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), you can install the prototype instead of the published plugin to see if it works for what you're trying to do.

It adds a `mode` option to the page-gallery config, which can be set to:
* "auto" (default) - display the first image found in the page, unless there isn't one, then display page content
* "image" - the current behavior, just displays the first image found, or falls back to just showing the filename
* "content" - displays page content, doesn't even try to display the first image found

**Comment by tokenshift** [comment]
This has now been published as version 0.6.0.
