### ISSUE TITLE
Filter bar not working

### ISSUE THREAD

**Issue by Cammagno** [tokenshift/obsidian-page-gallery#58]
For some reason, for me the filter bar doesn't work

I get these errors in the console:

![image](https://github.com/tokenshift/obsidian-page-gallery/assets/95725064/baa63a08-3df5-4e39-85de-0afec0aa029e)

I paste here one of my code block, to show if I'm doing something wrong, but it's the same with all of them:

![image](https://github.com/tokenshift/obsidian-page-gallery/assets/95725064/b2cb906d-a289-4f7a-8eca-b0505cee108b)

I'll be happy to provide any other useful info that can help to solve the issue.

Great plugin, BTW!

**Comment by tokenshift** [comment]
Reproduced via:

* Add a property/frontmatter to a page with a `null` value
* Input a filter string that doesn't match the page's path or tags, so that `matchFilter` attempts to look for a match in other page metadata (if the path or tags match, `matchFilter` won't bother looking at other metadata, so the `null` won't be encountered).

Fix coming soon.
